using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LevenshteinDistanceAlgorithm
{
static internal class JsonData
    {
        public static (string id, string name)[] Groups = new[] {
("01","NEW GUNNY BAGS"), ("02","S / HAND GUNNY BAGS"), ("03","EA BAG & CORDAGE PRODUCTS"), ("04","JUTE & SISAL PRODUCTS"), ("05","GROUP FIVE"), ("06","GROUP SIX"), ("07","SEEDS"), ("08","UNGA FEEDS"), ("09","MISCELLANEOUS FEEDS"), ("10","BRAN & POLLARD"), ("11","MEAT & BONE MEAL"), ("12","FERTILIZERS"), ("13","FERTILIZERS"), ("14","FERTILIZERS"), ("15","COOPER PRODUCTS"), ("16","KENYA SWISS PRODUCTS"), ("17","TWIGA CHEMICAL PRODUCTS"), ("18","MURPHY CHEMICAL PRODUCTS"), ("19","CROP PROTECTION CHEMICAL PRODUCTS"), ("20","MISC. & VET PRODUCTS"), ("21"," PIG & POULTRY PRODUCTS"), ("22","GARDEN TOOLS & EQUIPMENTS"), ("23","FENCING WIRES & EQUIPMENTS"), ("24","CEMENT"), ("25","BUILDING MATERIAL & PIPING"), ("26","BRUSHES & PAINTS"), ("27","GENERAL HARDWARE"), ("28","TOOLS & BELTONG"), ("29","TYRES & TUBES"), ("30","CLOTHING & BLANKETS"), ("31","CLOTHING & BLANKETS"), ("32","HOUSEHOLD GOODS"), ("33","BICYLES & STATIONERY"), ("34","MISCELLANEOUS ITEMS"), ("35","CAMPING EQUIPMENTS"), ("36","CLAAS PRODUCTS"), ("37","OTHER MACHINERY PRODUCTS"), ("38","GROUP THIRTY-EIGHT"), ("39","GROUP THIRTY-NINE"), ("40","GROUP FORTY"), ("41","GROUP FORTY-ONE"), ("42","VEGETABLE SEEDS"), ("43","WOOL"), ("44","GROUP FORTY-FOUR"), ("45","WOOL") };
    }
}
